<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib tagdir="/WEB-INF/tags/" prefix="t"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>

<t:layout title="Products">
    <jsp:attribute name="actions">
        <a href="${pageContext.request.contextPath}/products?action=create" class="btn btn-success">
            <i class="fas fa-plus me-1"></i>Create Product
        </a>
    </jsp:attribute>

    <jsp:body>
        <c:if test="${param.msg == 'created'}">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                Product created successfully. SKU was auto-generated by category.
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        </c:if>
        <c:if test="${param.msg == 'updated'}">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                Product updated successfully.
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        </c:if>
        <c:if test="${param.msg == 'variants_created'}">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                Variants generated successfully. <c:if test="${not empty param.count}">Count: ${param.count}</c:if>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        </c:if>
        <c:set var="columns" value='${["Index", "SKU", "Product Name", "Category", "Actions"]}' />
        <t:table id="productTable" columns="${columns}">
            <jsp:attribute name="head">
                <form action="${pageContext.request.contextPath}/products" method="get" class="m-0">
                    <input type="hidden" name="size" value="${empty size ? 10 : size}">
                    <div class="form-row mb-2">
                        <div class="col-md-4">
                            <label class="mb-1 font-weight-bold">SKU</label>
                            <input type="text" name="filterSku" class="form-control" placeholder="SKU..." value="${filterSku}">
                        </div>
                        <div class="col-md-4">
                            <label class="mb-1 font-weight-bold">Product Name</label>
                            <input type="text" name="filterName" class="form-control" placeholder="Product name..." value="${filterName}">
                        </div>
                        <div class="col-md-4 d-flex align-items-end">
                            <button type="submit" class="btn btn-primary me-2">Search</button>
                            <a href="${pageContext.request.contextPath}/products" class="btn btn-outline-secondary">Reset</a>
                        </div>
                    </div>
                </form>
            </jsp:attribute>

            <jsp:attribute name="foot">
                <t:pagination page="${page}" pages="${totalPages}" size="${size}" total="${total}"
                    url="${pageContext.request.contextPath}/products"
                    include="[name='filterSku'], [name='filterName']" />
            </jsp:attribute>

            <jsp:body>
                <c:if test="${not empty products}">
                    <c:forEach var="p" items="${products}" varStatus="st">
                        <tr>
                            <td class="text-center">${(page - 1) * size + st.index + 1}</td>
                            <td><strong class="text-primary">${p.sku}</strong></td>
                            <td>${p.name}</td>
                            <td>${p.categoryName} <c:if test="${not empty p.categoryCode}"><small class="text-muted">(${p.categoryCode})</small></c:if></td>
                            <td class="text-center">
                                <button type="button"
                                        class="btn btn-sm btn-outline-secondary me-1 btn-view-product"
                                        data-product-id="${p.productId}"
                                        title="View">
                                    View
                                </button>
                                <a href="${pageContext.request.contextPath}/products?action=edit&id=${p.productId}&page=${page}&size=${size}" class="btn btn-sm btn-outline-primary me-1" title="Edit">Edit</a>
                                <a href="${pageContext.request.contextPath}/products?action=variants&id=${p.productId}&page=${page}&size=${size}" class="btn btn-sm btn-outline-info" title="Manage Variants">Variants</a>
                            </td>
                        </tr>
                    </c:forEach>
                </c:if>
                <c:if test="${empty products}">
                    <tr>
                        <td colspan="5" class="text-center text-muted py-4">No products found. Create a product to get started.</td>
                    </tr>
                </c:if>
            </jsp:body>
        </t:table>

        <!-- Create Product Modal -->
        <div class="modal fade" id="createProductModal" tabindex="-1" aria-labelledby="createProductModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content shadow-lg border-0">
                    <form action="${pageContext.request.contextPath}/products" method="post">
                        <input type="hidden" name="action" value="create">
                        <div class="modal-header bg-success text-white rounded-0">
                            <h5 class="modal-title d-flex align-items-center" id="createProductModalLabel">
                                <i class="fas fa-plus-circle me-2"></i>Create Product
                            </h5>
                            <button type="button" class="btn-close btn-close-white" aria-label="Close" id="createModalCloseBtn"></button>
                        </div>
                        <div class="modal-body p-4">
                            <c:if test="${param.msg == 'no_uom'}">
                                <div class="alert alert-danger alert-dismissible fade show mb-3 py-2" role="alert">
                                    <i class="fas fa-exclamation-triangle me-2"></i>
                                    Cannot create product: no Unit of Measure (UOM) defined. Please create at least one UOM in the system first.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            </c:if>
                            <div class="alert alert-light border mb-3 py-2 small d-flex align-items-center" role="status">
                                <i class="fas fa-barcode text-muted me-2"></i>
                                <span>SKU is auto-generated from category (e.g., TSH-001, PANTS-001).</span>
                            </div>
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Product Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control form-control-sm" required placeholder="Enter product name">
                            </div>
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Category <span class="text-danger">*</span></label>
                                <select name="categoryId" class="form-select form-select-sm" required>
                                    <option value="">-- Select category --</option>
                                    <c:forEach var="c" items="${categories}">
                                        <option value="${c.categoryId}">${c.name}<c:if test="${not empty categoryDisplayCodeMap[c.categoryId]}"> (${categoryDisplayCodeMap[c.categoryId]})</c:if></option>
                                    </c:forEach>
                                </select>
                            </div>
                            <hr class="my-3">
                            <p class="small text-muted mb-2 fw-semibold"><i class="fas fa-ruler-combined me-1"></i> Dimensions &amp; weight (optional)</p>
                            <div class="row g-2">
                                <div class="col-6">
                                    <label class="form-label small">Weight (kg)</label>
                                    <input type="number" step="0.01" name="weight" class="form-control form-control-sm" placeholder="0">
                                </div>
                                <div class="col-6">
                                    <label class="form-label small">Length (cm)</label>
                                    <input type="number" step="0.01" name="length" class="form-control form-control-sm" placeholder="0">
                                </div>
                                <div class="col-6">
                                    <label class="form-label small">Width (cm)</label>
                                    <input type="number" step="0.01" name="width" class="form-control form-control-sm" placeholder="0">
                                </div>
                                <div class="col-6">
                                    <label class="form-label small">Height (cm)</label>
                                    <input type="number" step="0.01" name="height" class="form-control form-control-sm" placeholder="0">
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer border-top bg-light rounded-0">
                            <button type="button" class="btn btn-outline-secondary btn-sm" id="createModalCancelBtn">Cancel</button>
                            <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-save me-1"></i>Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Edit Product Modal -->
        <div class="modal fade" id="editProductModal" tabindex="-1" aria-labelledby="editProductModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content shadow-lg border-0">
                    <c:if test="${not empty editProduct}">
                        <form action="${pageContext.request.contextPath}/products" method="post" id="editProductForm">
                            <input type="hidden" name="action" value="update">
                            <input type="hidden" name="productId" value="${editProduct.productId}">
                            <div class="modal-header bg-primary text-white rounded-0">
                                <h5 class="modal-title d-flex align-items-center" id="editProductModalLabel">
                                    <i class="fas fa-edit me-2"></i>Edit Product
                                </h5>
                                <button type="button" class="btn-close btn-close-white" aria-label="Close" id="editModalCloseBtn"></button>
                            </div>
                            <div class="modal-body p-4">
                                <div class="alert alert-light border mb-3 py-2 small d-flex align-items-center" role="status">
                                    <i class="fas fa-barcode text-muted me-2"></i>
                                    <span>SKU (read-only): <strong class="text-primary">${editProduct.sku}</strong></span>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label fw-semibold">Product Name <span class="text-danger">*</span></label>
                                    <input type="text" name="name" class="form-control form-control-sm" required value="${editProduct.name}" placeholder="Product name">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label fw-semibold">Category</label>
                                    <select name="categoryId" class="form-select form-select-sm">
                                        <c:forEach var="c" items="${categories}">
                                            <option value="${c.categoryId}" ${c.categoryId == editProduct.categoryId ? 'selected' : ''}>${c.name}<c:if test="${not empty categoryDisplayCodeMap[c.categoryId]}"> (${categoryDisplayCodeMap[c.categoryId]})</c:if></option>
                                        </c:forEach>
                                    </select>
                                </div>
                                <hr class="my-3">
                                <p class="small text-muted mb-2 fw-semibold"><i class="fas fa-ruler-combined me-1"></i> Dimensions &amp; weight</p>
                                <div class="row g-2">
                                    <div class="col-6">
                                        <label class="form-label small">Weight (kg)</label>
                                        <input type="number" step="0.01" name="weight" class="form-control form-control-sm" value="${editProduct.weight}" placeholder="0">
                                    </div>
                                    <div class="col-6">
                                        <label class="form-label small">Length (cm)</label>
                                        <input type="number" step="0.01" name="length" class="form-control form-control-sm" value="${editProduct.length}" placeholder="0">
                                    </div>
                                    <div class="col-6">
                                        <label class="form-label small">Width (cm)</label>
                                        <input type="number" step="0.01" name="width" class="form-control form-control-sm" value="${editProduct.width}" placeholder="0">
                                    </div>
                                    <div class="col-6">
                                        <label class="form-label small">Height (cm)</label>
                                        <input type="number" step="0.01" name="height" class="form-control form-control-sm" value="${editProduct.height}" placeholder="0">
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer border-top bg-light rounded-0">
                                <button type="button" class="btn btn-outline-secondary btn-sm" id="editModalCancelBtn">Cancel</button>
                                <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-save me-1"></i>Update</button>
                            </div>
                        </form>
                    </c:if>
                </div>
            </div>
        </div>

        <!-- View Product Modal (read-only, show variants) -->
        <div class="modal fade" id="viewProductModal" tabindex="-1" aria-labelledby="viewProductModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg">
                <div class="modal-content shadow-lg border-0">
                    <div class="modal-header bg-secondary text-white rounded-0">
                        <h5 class="modal-title d-flex align-items-center" id="viewProductModalLabel">
                            <i class="fas fa-eye me-2"></i>Product Detail
                        </h5>
                        <button type="button" class="btn-close btn-close-white" aria-label="Close" id="viewModalCloseBtn"></button>
                    </div>
                    <div class="modal-body p-4">
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <p class="mb-1 small text-muted">SKU</p>
                                <p class="mb-2"><code id="viewSku"></code></p>
                            </div>
                            <div class="col-md-6">
                                <p class="mb-1 small text-muted">Created At</p>
                                <p class="mb-2" id="viewCreatedAt">-</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <p class="mb-1 small text-muted">Product Name</p>
                                <p class="mb-2 fw-semibold" id="viewName"></p>
                            </div>
                            <div class="col-md-6">
                                <p class="mb-1 small text-muted">Category</p>
                                <p class="mb-2" id="viewCategory"></p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-3">
                                <p class="mb-1 small text-muted">UOM</p>
                                <p class="mb-2" id="viewUom">-</p>
                            </div>
                            <div class="col-md-9">
                                <p class="mb-1 small text-muted">Dimensions &amp; Weight</p>
                                <p class="mb-2 small" id="viewDimensions">-</p>
                            </div>
                        </div>

                        <hr class="my-3">
                        <h6 class="fw-semibold mb-2 d-flex align-items-center">
                            <i class="fas fa-th-list me-2"></i>Variants
                        </h6>
                        <div class="table-responsive rounded border">
                            <table class="table table-sm table-hover mb-0">
                                <thead class="table-secondary">
                                    <tr>
                                        <th class="border-0 text-center">Variant SKU</th>
                                        <th class="border-0 text-center">Color</th>
                                        <th class="border-0 text-center">Size</th>
                                        <th class="border-0 text-center">Status</th>
                                        <th class="border-0 text-center">On hand</th>
                                        <th class="border-0 text-center">Available</th>
                                    </tr>
                                </thead>
                                <tbody id="viewVariantTbody">
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="modal-footer border-top bg-light rounded-0">
                        <button type="button" class="btn btn-outline-secondary btn-sm" id="viewModalFooterCloseBtn">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Variant Modal: fit màn hình, nội dung cuộn bên trong -->
        <div class="modal fade" id="variantMatrixModal" tabindex="-1" aria-labelledby="variantModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable variant-modal-dialog">
                <div class="modal-content shadow-lg border-0">
                    <c:if test="${not empty variantMatrixProduct}">
                        <div class="modal-header bg-info text-white rounded-0">
                            <h5 class="modal-title d-flex align-items-center" id="variantModalLabel">
                                <i class="fas fa-palette me-2"></i>Variants — ${variantMatrixProduct.sku}
                            </h5>
                            <button type="button" class="btn-close btn-close-white" aria-label="Close" id="variantModalCloseBtn"></button>
                        </div>
                        <div class="modal-body p-3 variant-modal-body">
                            <%-- Notifications are shown inside the modal for better UX --%>
                            <c:if test="${param.msg == 'variant_has_stock'}">
                                <div class="alert alert-warning alert-dismissible fade show mb-3 py-2" role="alert">
                                    <i class="fas fa-exclamation-triangle me-2"></i>
                                    <strong>Cannot set to Inactive:</strong> This variant still has stock in the warehouse. Please clear all stock before setting it to Inactive.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            </c:if>
                            <c:if test="${param.msg == 'variant_inactive'}">
                                <div class="alert alert-info alert-dismissible fade show mb-3 py-2" role="alert">
                                    <i class="fas fa-info-circle me-2"></i>The variant has been set to Inactive.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            </c:if>
                            <c:if test="${param.msg == 'variant_active'}">
                                <div class="alert alert-success alert-dismissible fade show mb-3 py-2" role="alert">
                                    <i class="fas fa-check-circle me-2"></i>The variant has been reactivated (Active).
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            </c:if>

                            <p class="small text-muted mb-3">Select colors (swatches) and sizes by category, then click Generate Variant to create combinations. You can set variants to Inactive below.</p>

                            <form id="variantMatrixForm" action="${pageContext.request.contextPath}/products" method="post">
                                <input type="hidden" name="action" value="generateVariants">
                                <input type="hidden" name="productId" value="${variantMatrixProduct.productId}">

                                <div class="card border-0 bg-light mb-3">
                                    <div class="card-body py-3">
                                        <label class="form-label fw-semibold mb-2"><i class="fas fa-fill-drip text-info me-1"></i> Colors (Color swatches)</label>
                                        <div class="d-flex flex-wrap gap-2">
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Red|#FF0000"><span class="chip-swatch" style="background:#FF0000;"></span><span>Red</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Blue|#0000FF"><span class="chip-swatch" style="background:#0000FF;"></span><span>Blue</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Black|#000000"><span class="chip-swatch" style="background:#000000;"></span><span>Black</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="White|#FFFFFF"><span class="chip-swatch chip-swatch-white"></span><span>White</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Green|#008000"><span class="chip-swatch" style="background:#008000;"></span><span>Green</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Yellow|#FFFF00"><span class="chip-swatch" style="background:#FFFF00;"></span><span>Yellow</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Gray|#808080"><span class="chip-swatch" style="background:#808080;"></span><span>Gray</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Navy|#000080"><span class="chip-swatch" style="background:#000080;"></span><span>Navy</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Pink|#FFC0CB"><span class="chip-swatch" style="background:#FFC0CB;"></span><span>Pink</span></label>
                                            <label class="variant-color-chip"><input type="checkbox" name="colors" value="Orange|#FFA500"><span class="chip-swatch" style="background:#FFA500;"></span><span>Orange</span></label>
                                        </div>
                                    </div>
                                </div>

                                <div class="card border-0 bg-light mb-3">
                                    <div class="card-body py-3">
                                        <label class="form-label fw-semibold mb-2"><i class="fas fa-ruler me-1 text-info"></i> Size</label>
                                        <c:choose>
                                            <c:when test="${variantMatrixCategory != null && variantMatrixCategory.sizeType == 'LETTER'}">
                                                <p class="small text-muted mb-2">For top categories (TSH, HD): choose letter sizes.</p>
                                                <div class="d-flex flex-wrap gap-2">
                                                    <c:forEach var="s" items="${['XS','S','M','L','XL']}">
                                                        <label class="variant-size-chip">
                                                            <input type="checkbox" name="sizes" value="${s}"> ${s}
                                                        </label>
                                                    </c:forEach>
                                                </div>
                                            </c:when>
                                            <c:otherwise>
                                                <p class="small text-muted mb-2">For bottom categories (pants): choose numeric sizes.</p>
                                                <div class="d-flex flex-wrap gap-2">
                                                    <c:forEach var="n" begin="26" end="40">
                                                        <label class="variant-size-chip">
                                                            <input type="checkbox" name="sizes" value="${n}"> ${n}
                                                        </label>
                                                    </c:forEach>
                                                </div>
                                            </c:otherwise>
                                        </c:choose>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-success"><i class="fas fa-plus-circle me-1"></i>Generate Variant</button>
                            </form>

                            <hr class="my-4">
                            <h6 class="fw-semibold mb-2"><i class="fas fa-list me-1"></i> Variant list</h6>
                            <div class="table-responsive rounded border">
                                <table class="table table-sm table-hover mb-0 table-variant-list">
                                    <thead class="table-info">
                                        <tr>
                                            <th class="border-0 text-center" style="width:28%;">Variant SKU</th>
                                            <th class="border-0 text-center" style="width:22%;">Color</th>
                                            <th class="border-0 text-center" style="width:12%;">Size</th>
                                            <th class="border-0 text-center" style="width:18%;">Status</th>
                                            <th class="border-0 text-center" style="width:20%;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <c:forEach var="v" items="${variantMatrixProduct.variants}">
                                            <tr>
                                                <td class="text-center"><code class="small">${v.variantSku}</code></td>
                                                <td class="text-center">
                                                    <c:if test="${not empty v.colorHex}">
                                                        <span class="rounded border d-inline-block me-1" style="width:14px;height:14px;background:${v.colorHex};vertical-align:middle;"></span>
                                                    </c:if>
                                                    ${v.color}
                                                </td>
                                                <td class="text-center">${v.size}</td>
                                                <td class="text-center"><span class="badge bg-${v.status == 'ACTIVE' ? 'success' : 'secondary'}">${v.status}</span></td>
                                                <td class="text-center">
                                                    <c:if test="${v.status == 'ACTIVE'}">
                                                        <form method="post" action="${pageContext.request.contextPath}/products" class="d-inline">
                                                            <input type="hidden" name="action" value="inactiveVariant">
                                                            <input type="hidden" name="variantId" value="${v.variantId}">
                                                            <button type="submit" class="btn btn-sm btn-outline-warning btn-inactive-variant">Inactive</button>
                                                        </form>
                                                    </c:if>
                                                    <c:if test="${v.status == 'INACTIVE'}">
                                                        <form method="post" action="${pageContext.request.contextPath}/products" class="d-inline">
                                                            <input type="hidden" name="action" value="activeVariant">
                                                            <input type="hidden" name="variantId" value="${v.variantId}">
                                                            <button type="submit" class="btn btn-sm btn-outline-success btn-active-variant">Active</button>
                                                        </form>
                                                    </c:if>
                                                </td>
                                            </tr>
                                        </c:forEach>
                                        <c:if test="${empty variantMatrixProduct.variants}">
                                            <tr><td colspan="5" class="text-muted text-center py-3">No variants yet. Select colors and sizes, then click Generate Variant.</td></tr>
                                        </c:if>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </c:if>
                </div>
            </div>
        </div>
        <style>
            /* Modal variant fit màn hình: chiều cao tối đa theo viewport, body cuộn bên trong */
            .variant-modal-dialog { max-width: min(96vw, 720px); max-height: 90vh; }
            .variant-modal-dialog .modal-content { max-height: 90vh; display: flex; flex-direction: column; }
            .variant-modal-body { overflow-y: auto; overflow-x: hidden; flex: 1; min-height: 0; }
            .variant-color-chip { display: inline-flex; align-items: center; border: 1px solid #dee2e6; border-radius: 6px; padding: 5px 8px; cursor: pointer; margin: 2px; background: #fff; font-size: 0.9rem; }
            .variant-color-chip:hover { border-color: #0dcaf0; background: #f8f9fa; }
            .variant-color-chip input { margin-right: 5px; }
            .chip-swatch { width: 16px; height: 16px; border-radius: 4px; border: 1px solid #dee2e6; margin-right: 5px; display: inline-block; }
            .chip-swatch-white { background: #fff !important; border: 1px solid #adb5bd !important; }
            .variant-size-chip { display: inline-flex; align-items: center; border: 1px solid #dee2e6; border-radius: 6px; padding: 5px 10px; cursor: pointer; margin: 2px; background: #fff; font-size: 0.9rem; }
            .variant-size-chip:hover { border-color: #0dcaf0; background: #f8f9fa; }
            .variant-size-chip input { margin-right: 5px; }
            .table-variant-list { table-layout: fixed; width: 100%; }
            .table-variant-list th, .table-variant-list td { vertical-align: middle; }
            #viewVariantTbody td { vertical-align: middle; }
        </style>

        <script>
        (function() {
            var openCreate = ${openCreateModal == true ? 'true' : 'false'};
            var openEdit = ${openEditModal == true ? 'true' : 'false'};
            var openVariant = ${openVariantModal == true ? 'true' : 'false'};

            document.addEventListener('DOMContentLoaded', function() {
                var ctx = '${pageContext.request.contextPath}';

                // Edit modal: dùng new bootstrap.Modal() (tương thích Bootstrap 4 & 5, không dùng getOrCreateInstance)
                var editModalEl = document.getElementById('editProductModal');
                if (editModalEl) {
                    var editModalInstance = null;
                    function closeEditModal() {
                        if (editModalInstance && typeof editModalInstance.hide === 'function') editModalInstance.hide();
                        window.location.href = ctx + '/products';
                    }
                    var closeBtn = document.getElementById('editModalCloseBtn');
                    if (closeBtn) closeBtn.addEventListener('click', closeEditModal);
                    var cancelBtn = document.getElementById('editModalCancelBtn');
                    if (cancelBtn) cancelBtn.addEventListener('click', closeEditModal);
                    if (openEdit) {
                        editModalInstance = new bootstrap.Modal(editModalEl);
                        editModalInstance.show();
                    }
                }

                // Create modal: nút X và Cancel đóng và quay lại list (giống Edit modal)
                var createModalEl = document.getElementById('createProductModal');
                if (createModalEl) {
                    var createModalInstance = null;
                    function closeCreateModal() {
                        if (createModalInstance && typeof createModalInstance.hide === 'function') createModalInstance.hide();
                        window.location.href = ctx + '/products';
                    }
                    var createCloseBtn = document.getElementById('createModalCloseBtn');
                    if (createCloseBtn) createCloseBtn.addEventListener('click', closeCreateModal);
                    var createCancelBtn = document.getElementById('createModalCancelBtn');
                    if (createCancelBtn) createCancelBtn.addEventListener('click', closeCreateModal);
                    if (openCreate) {
                        createModalInstance = new bootstrap.Modal(createModalEl);
                        createModalInstance.show();
                    }
                }
                // Variant modal: nút X đóng và quay lại list (giống Edit modal)
                var variantModalEl = document.getElementById('variantMatrixModal');
                if (variantModalEl) {
                    var variantModalInstance = null;
                    function closeVariantModal() {
                        if (variantModalInstance && typeof variantModalInstance.hide === 'function') variantModalInstance.hide();
                        window.location.href = ctx + '/products';
                    }
                    var variantCloseBtn = document.getElementById('variantModalCloseBtn');
                    if (variantCloseBtn) variantCloseBtn.addEventListener('click', closeVariantModal);
                    if (openVariant) {
                        variantModalInstance = new bootstrap.Modal(variantModalEl);
                        variantModalInstance.show();
                    }
                }

                // Inactive/Active: submit bằng form, không confirm

                // View product detail (AJAX -> /products?action=detail&id=...)
                var viewModalEl = document.getElementById('viewProductModal');
                var viewModalInstance = viewModalEl ? new bootstrap.Modal(viewModalEl) : null;
                var viewSkuEl = document.getElementById('viewSku');
                var viewNameEl = document.getElementById('viewName');
                var viewCategoryEl = document.getElementById('viewCategory');
                var viewUomEl = document.getElementById('viewUom');
                var viewDimensionsEl = document.getElementById('viewDimensions');
                var viewCreatedAtEl = document.getElementById('viewCreatedAt');
                var viewVariantTbody = document.getElementById('viewVariantTbody');
                var viewModalCloseBtn = document.getElementById('viewModalCloseBtn');
                var viewModalFooterCloseBtn = document.getElementById('viewModalFooterCloseBtn');

                function textOrDash(value) {
                    if (value === null || value === undefined || value === '') return '-';
                    return value;
                }

                function formatDimensions(p) {
                    var parts = [];
                    if (p.weight != null) parts.push('Weight: ' + p.weight + ' kg');
                    var hasL = p.length != null;
                    var hasW = p.width != null;
                    var hasH = p.height != null;
                    if (hasL || hasW || hasH) {
                        var dims = 'LxWxH: ' +
                            (hasL ? p.length : '0') + ' x ' +
                            (hasW ? p.width : '0') + ' x ' +
                            (hasH ? p.height : '0') + ' cm';
                        parts.push(dims);
                    }
                    return parts.length ? parts.join(' | ') : '-';
                }

                function renderVariants(variants) {
                    if (!viewVariantTbody) return;
                    viewVariantTbody.innerHTML = '';
                    if (!variants || !variants.length) {
                        var trEmpty = document.createElement('tr');
                        var tdEmpty = document.createElement('td');
                        tdEmpty.colSpan = 6;
                        tdEmpty.className = 'text-center text-muted py-3';
                        tdEmpty.textContent = 'No variants.';
                        trEmpty.appendChild(tdEmpty);
                        viewVariantTbody.appendChild(trEmpty);
                        return;
                    }
                    variants.forEach(function(v) {
                        var tr = document.createElement('tr');

                        var tdSku = document.createElement('td');
                        tdSku.className = 'text-center';
                        var code = document.createElement('code');
                        code.className = 'small';
                        code.textContent = v.variantSku || '';
                        tdSku.appendChild(code);
                        tr.appendChild(tdSku);

                        var tdColor = document.createElement('td');
                        tdColor.className = 'text-center';
                        if (v.colorHex) {
                            var sw = document.createElement('span');
                            sw.className = 'rounded border d-inline-block me-1';
                            sw.style.width = '14px';
                            sw.style.height = '14px';
                            sw.style.background = v.colorHex;
                            sw.style.verticalAlign = 'middle';
                            tdColor.appendChild(sw);
                        }
                        tdColor.appendChild(document.createTextNode(v.color || ''));
                        tr.appendChild(tdColor);

                        var tdSize = document.createElement('td');
                        tdSize.className = 'text-center';
                        tdSize.textContent = v.size || '';
                        tr.appendChild(tdSize);

                        var tdStatus = document.createElement('td');
                        tdStatus.className = 'text-center';
                        var spanStatus = document.createElement('span');
                        var status = (v.status || '').toUpperCase();
                        spanStatus.className = 'badge bg-' + (status === 'ACTIVE' ? 'success' : 'secondary');
                        spanStatus.textContent = status || '-';
                        tdStatus.appendChild(spanStatus);
                        tr.appendChild(tdStatus);

                        var tdOnHand = document.createElement('td');
                        tdOnHand.className = 'text-center';
                        tdOnHand.textContent = v.totalQtyOnHand != null ? v.totalQtyOnHand : '0';
                        tr.appendChild(tdOnHand);

                        var tdAvailable = document.createElement('td');
                        tdAvailable.className = 'text-center';
                        tdAvailable.textContent = v.totalQtyAvailable != null ? v.totalQtyAvailable : '0';
                        tr.appendChild(tdAvailable);

                        viewVariantTbody.appendChild(tr);
                    });
                }

                function bindViewButtons() {
                    var buttons = document.querySelectorAll('.btn-view-product');
                    if (!buttons || !buttons.length || !viewModalInstance) return;
                    buttons.forEach(function(btn) {
                        btn.addEventListener('click', function() {
                            var id = this.getAttribute('data-product-id');
                            if (!id) return;
                            fetch(ctx + '/products?action=detail&id=' + encodeURIComponent(id), {
                                headers: { 'Accept': 'application/json' }
                            })
                            .then(function(res) {
                                if (!res.ok) throw new Error('Failed to load product');
                                return res.json();
                            })
                            .then(function(data) {
                                if (!data) return;
                                if (viewSkuEl) viewSkuEl.textContent = textOrDash(data.sku);
                                if (viewNameEl) viewNameEl.textContent = textOrDash(data.name);
                                if (viewCategoryEl) viewCategoryEl.textContent = textOrDash(data.categoryName);
                                if (viewUomEl) viewUomEl.textContent = textOrDash(data.uomName);
                                if (viewDimensionsEl) viewDimensionsEl.textContent = formatDimensions(data);
                                if (viewCreatedAtEl) viewCreatedAtEl.textContent = textOrDash(data.createdAt);
                                renderVariants(data.variants || []);
                                viewModalInstance.show();
                            })
                            .catch(function() {
                                alert('Cannot load product information. Please try again.');
                            });
                        });
                    });
                }

                bindViewButtons();

                // Nút X và nút Close trong footer: đóng modal (không redirect)
                function bindViewCloseButtons() {
                    if (!viewModalInstance) return;
                    if (viewModalCloseBtn) {
                        viewModalCloseBtn.addEventListener('click', function() {
                            viewModalInstance.hide();
                        });
                    }
                    if (viewModalFooterCloseBtn) {
                        viewModalFooterCloseBtn.addEventListener('click', function() {
                            viewModalInstance.hide();
                        });
                    }
                }

                bindViewCloseButtons();
            });
        })();
        </script>
    </jsp:body>
</t:layout>
