package controller;

import dao.CategoryDAO;
import dao.ProductDAO;
import dao.ProductVariantDAO;
import dao.UomDAO;
import dto.ProductDetailDTO;
import dto.ProductListDTO;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Category;
import model.Product;
import model.User;
import util.RequestUtil;

/**
 * Product management: list (paginated), create, edit (no delete), variant matrix (generate + inactive).
 * SKU auto-generated by category. No barcode in UI.
 */
@WebServlet(name = "ProductController", urlPatterns = {"/products"})
public class ProductController extends HttpServlet {

    private static final int DEFAULT_PAGE = 1;
    private static final int DEFAULT_SIZE = 10;
    /** Các size phân trang hợp lệ (đồng bộ với t:pagination). */
    private static final List<Integer> PAGE_SIZES = Arrays.asList(5, 10, 20, 50);

    /** Base URL cho redirect (VD: /warehouse_management_swp391/products). */
    private String base() {
        return getServletContext().getContextPath() + "/products";
    }

    // --- GET: list / create form / edit form / variant matrix / detail (JSON) ---

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");
        String action = request.getParameter("action");
        try {
            switch (action == null ? "" : action) {
                case "detail":
                    handleGetDetail(request, response);
                    break;
                case "create":
                    request.setAttribute("openCreateModal", true);
                    handleList(request, response);
                    break;
                case "edit":
                    forwardEdit(request, response);
                    break;
                case "variants":
                    forwardVariantMatrix(request, response);
                    break;
                default:
                    handleList(request, response);
                    break;
            }
        } catch (Exception ex) {
            Logger.getLogger(ProductController.class.getName()).log(Level.SEVERE, null, ex);
            throw new ServletException(ex);
        }
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");
        String action = request.getParameter("action");
        try {
            switch (action == null ? "" : action) {
                case "create":
                    handleCreate(request, response);
                    break;
                case "update":
                    handleUpdate(request, response);
                    break;
                case "generateVariants":
                    handleGenerateVariants(request, response);
                    break;
                case "inactiveVariant":
                    handleInactiveVariant(request, response);
                    break;
                case "activeVariant":
                    handleActiveVariant(request, response);
                    break;
                default:
                    response.sendRedirect(base());
                    break;
            }
        } catch (Exception ex) {
            Logger.getLogger(ProductController.class.getName()).log(Level.SEVERE, null, ex);
            throw new ServletException(ex);
        }
    }

    // --- List (paginated, filter by SKU/name) ---

    private void handleList(HttpServletRequest request, HttpServletResponse response) throws Exception {
        int page = RequestUtil.parseInt(request.getParameter("page"), DEFAULT_PAGE);
        int size = RequestUtil.parseInt(request.getParameter("size"), DEFAULT_SIZE);
        if (!PAGE_SIZES.contains(size)) size = DEFAULT_SIZE;
        if (page < 1) page = 1;

        String filterSku = trimParam(request.getParameter("filterSku"));
        String filterName = trimParam(request.getParameter("filterName"));

        ProductDAO productDAO = new ProductDAO();
        int totalRecords = productDAO.countAllProducts(filterSku, filterName);
        int totalPages = totalRecords == 0 ? 1 : (int) Math.ceil((double) totalRecords / size);
        if (page > totalPages) page = totalPages;
        int offset = (page - 1) * size;

        String sortBy = request.getParameter("sortBy");
        if (sortBy == null || sortBy.isBlank()) sortBy = "product_id";
        String sortOrder = "DESC".equalsIgnoreCase(request.getParameter("sortOrder")) ? "DESC" : "ASC";

        List<ProductListDTO> products = productDAO.getAllProducts(size, offset, filterSku, filterName, null, sortBy, sortOrder);
        List<Category> categories = new CategoryDAO().getAll();
        Map<Long, Category> categoryMap = categories.stream().collect(Collectors.toMap(Category::getCategoryId, c -> c));

        // Gán categoryCode (viết tắt hiển thị: TSH, HD, PANTS...; không dùng C1, C2), sizeType cho từng product
        Map<Long, String> categoryDisplayCodeMap = new LinkedHashMap<>();
        for (Category c : categories) {
            categoryDisplayCodeMap.put(c.getCategoryId(), getDisplayCodeFromCategory(c));
        }
        for (ProductListDTO p : products) {
            if (p.getCategoryId() != null && categoryMap.containsKey(p.getCategoryId())) {
                Category c = categoryMap.get(p.getCategoryId());
                p.setCategoryCode(getDisplayCodeFromCategory(c));
                p.setSizeType(c.getSizeType());
            } else {
                p.setCategoryCode("");
                p.setSizeType("NUMBER");
            }
        }

        request.setAttribute("products", products);
        request.setAttribute("categories", categories);
        request.setAttribute("categoryDisplayCodeMap", categoryDisplayCodeMap);
        request.setAttribute("page", page);
        request.setAttribute("totalPages", totalPages);
        request.setAttribute("size", size);
        request.setAttribute("total", totalRecords);
        request.setAttribute("filterSku", filterSku);
        request.setAttribute("filterName", filterName);
        request.setAttribute("sortBy", sortBy);
        request.setAttribute("sortOrder", sortOrder);
        request.getRequestDispatcher("WEB-INF/views/product/product-list.jsp").forward(request, response);
    }

    /** Mở list kèm modal Edit (load product theo id). */
    private void forwardEdit(HttpServletRequest request, HttpServletResponse response) throws Exception {
        long id = RequestUtil.parseLong(request.getParameter("id"), -1);
        if (id <= 0) {
            response.sendRedirect(base());
            return;
        }
        ProductDetailDTO product = new ProductDAO().getProductById(id);
        if (product == null) {
            response.sendRedirect(base());
            return;
        }
        request.setAttribute("editProduct", product);
        request.setAttribute("openEditModal", true);
        handleList(request, response);
    }

    /** Mở list kèm modal Variant Matrix (ma trận màu × size). */
    private void forwardVariantMatrix(HttpServletRequest request, HttpServletResponse response) throws Exception {
        long id = RequestUtil.parseLong(request.getParameter("id"), -1);
        if (id <= 0) {
            response.sendRedirect(base());
            return;
        }
        ProductDetailDTO product = new ProductDAO().getProductById(id);
        if (product == null) {
            response.sendRedirect(base());
            return;
        }
        Category cat = product.getCategoryId() != null ? new CategoryDAO().getById(product.getCategoryId()) : null;
        boolean tshOrHd = cat != null && ("TSH".equalsIgnoreCase(cat.getCode()) || "HD".equalsIgnoreCase(cat.getCode())
                || (cat.getName() != null && (cat.getName().toLowerCase().contains("t-shirt") || cat.getName().toLowerCase().contains("hoodie"))));
        request.setAttribute("variantMatrixProduct", product);
        request.setAttribute("variantMatrixCategory", cat);
        request.setAttribute("variantMatrixTshOrHd", tshOrHd);
        request.setAttribute("openVariantModal", true);
        handleList(request, response);
    }

    // --- POST: Create / Update product ---

    private void handleCreate(HttpServletRequest request, HttpServletResponse response) throws Exception {
        String name = trimParam(request.getParameter("name"));
        long catId = RequestUtil.parseLong(request.getParameter("categoryId"), -1);
        Long categoryId = catId > 0 ? catId : null;
        if (name == null || name.isEmpty() || categoryId == null) {
            response.sendRedirect(base() + "?action=create&msg=invalid");
            return;
        }

        Category cat = new CategoryDAO().getById(categoryId);
        String prefix = (cat != null) ? getSkuPrefixFromCategory(cat) : ("C" + categoryId);
        String sku = new ProductDAO().getNextSkuForCategory(prefix);

        Product p = new Product();
        p.setSku(sku);
        p.setName(name);
        p.setCategoryId(categoryId);
        Long baseUomId = parseLongOpt(request.getParameter("baseUomId"));
        if (baseUomId == null) baseUomId = new UomDAO().getFirstId();
        p.setBaseUomId(baseUomId);
        p.setWeight(parseBigDecimal(request.getParameter("weight")));
        p.setLength(parseBigDecimal(request.getParameter("length")));
        p.setWidth(parseBigDecimal(request.getParameter("width")));
        p.setHeight(parseBigDecimal(request.getParameter("height")));

        try {
            new ProductDAO().insertProduct(p);
        } catch (IllegalStateException e) {
            response.sendRedirect(base() + "?action=create&msg=no_uom");
            return;
        }
        request.getSession().setAttribute("message", "Product created successfully.");
        response.sendRedirect(base());
    }

    private void handleUpdate(HttpServletRequest request, HttpServletResponse response) throws Exception {
        long productId = RequestUtil.parseLong(request.getParameter("productId"), -1);
        if (productId <= 0) {
            response.sendRedirect(base());
            return;
        }
        ProductDetailDTO existing = new ProductDAO().getProductById(productId);
        if (existing == null) {
            response.sendRedirect(base());
            return;
        }

        String name = trimParam(request.getParameter("name"));
        long catId = RequestUtil.parseLong(request.getParameter("categoryId"), -1);
        Long baseUomId = parseLongOpt(request.getParameter("baseUomId"));

        Product p = new Product();
        p.setProductId(productId);
        p.setSku(existing.getSku());
        p.setName(name != null && !name.isEmpty() ? name : existing.getName());
        p.setCategoryId(catId > 0 ? catId : existing.getCategoryId());
        p.setBaseUomId(baseUomId != null ? baseUomId : existing.getBaseUomId());
        p.setWeight(parseBigDecimal(request.getParameter("weight")));
        p.setLength(parseBigDecimal(request.getParameter("length")));
        p.setWidth(parseBigDecimal(request.getParameter("width")));
        p.setHeight(parseBigDecimal(request.getParameter("height")));

        new ProductDAO().updateProduct(p);
        request.getSession().setAttribute("message", "Product updated successfully.");
        response.sendRedirect(base());
    }

    // --- POST: Variant matrix (tạo tổ hợp màu × size) + Inactive variant ---

    private void handleGenerateVariants(HttpServletRequest request, HttpServletResponse response) throws Exception {
        long productId = RequestUtil.parseLong(request.getParameter("productId"), -1);
        if (productId <= 0) {
            response.sendRedirect(base());
            return;
        }
        ProductDetailDTO product = new ProductDAO().getProductById(productId);
        if (product == null) {
            response.sendRedirect(base());
            return;
        }

        String[] colorsParam = request.getParameterValues("colors");
        String[] sizesParam = request.getParameterValues("sizes");
        if (colorsParam == null || colorsParam.length == 0 || sizesParam == null || sizesParam.length == 0) {
            response.sendRedirect(base() + "?action=variants&id=" + productId + "&msg=invalid");
            return;
        }

        ProductVariantDAO variantDAO = new ProductVariantDAO();
        String productSku = product.getSku();
        int added = 0;

        for (String colorEntry : colorsParam) {
            if (colorEntry == null || colorEntry.isBlank()) continue;
            // Format: "Tên màu|#hex" hoặc chỉ "Tên màu"
            String colorName = colorEntry;
            String colorHex = null;
            if (colorEntry.contains("|")) {
                int i = colorEntry.indexOf('|');
                colorName = colorEntry.substring(0, i).trim();
                colorHex = colorEntry.substring(i + 1).trim();
                if (colorHex.isEmpty()) colorHex = null;
            }
            String colorCode = toColorCode(colorName);

            for (String size : sizesParam) {
                if (size == null || size.isBlank()) continue;
                size = size.trim();
                String variantSku = productSku + "-" + size + "-" + colorCode;
                if (variantDAO.existsByProductIdAndSku(productId, variantSku)) continue;
                variantDAO.insert(productId, variantSku, colorName, colorHex, size);
                added++;
            }
        }

        response.sendRedirect(base() + "?action=variants&id=" + productId + "&msg=variants_created&count=" + added);
    }

    private void handleInactiveVariant(HttpServletRequest request, HttpServletResponse response) throws Exception {
        long variantId = RequestUtil.parseLong(request.getParameter("variantId"), -1);
        if (variantId <= 0) {
            response.sendRedirect(base());
            return;
        }
        ProductVariantDAO variantDAO = new ProductVariantDAO();
        if (variantDAO.hasStockInWarehouse(variantId)) {
            Long productId = variantDAO.getProductIdByVariantId(variantId);
            String url = productId != null ? base() + "?action=variants&id=" + productId + "&msg=variant_has_stock" : base();
            response.sendRedirect(url);
            return;
        }
        variantDAO.updateStatus(variantId, "INACTIVE");
        Long productId = variantDAO.getProductIdByVariantId(variantId);
        if (productId != null) {
            response.sendRedirect(base() + "?action=variants&id=" + productId + "&msg=variant_inactive");
        } else {
            response.sendRedirect(base());
        }
    }

    private void handleActiveVariant(HttpServletRequest request, HttpServletResponse response) throws Exception {
        long variantId = RequestUtil.parseLong(request.getParameter("variantId"), -1);
        if (variantId <= 0) {
            response.sendRedirect(base());
            return;
        }
        ProductVariantDAO variantDAO = new ProductVariantDAO();
        variantDAO.updateStatus(variantId, "ACTIVE");
        Long productId = variantDAO.getProductIdByVariantId(variantId);
        if (productId != null) {
            response.sendRedirect(base() + "?action=variants&id=" + productId + "&msg=variant_active");
        } else {
            response.sendRedirect(base());
        }
    }

    // --- JSON: Chi tiết product (cho AJAX nếu cần) ---

    private void handleGetDetail(HttpServletRequest request, HttpServletResponse response) throws Exception {
        response.setContentType("application/json;charset=UTF-8");
        long productId = RequestUtil.parseLong(request.getParameter("id"), -1);
        if (productId <= 0) {
            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            response.getWriter().write("{\"error\":\"Invalid product ID\"}");
            return;
        }
        Long warehouseId = null;
        try {
            Object u = request.getSession(false) != null ? request.getSession(false).getAttribute("USER") : null;
            if (u instanceof User) {
                warehouseId = ((User) u).getWarehouseId();
            }
        } catch (Exception ignored) {}

        ProductDAO productDAO = new ProductDAO();
        ProductDetailDTO product = (warehouseId != null)
                ? productDAO.getProductById(productId, warehouseId)
                : productDAO.getProductById(productId);
        if (product == null) {
            response.setStatus(HttpServletResponse.SC_NOT_FOUND);
            response.getWriter().write("{\"error\":\"Product not found\"}");
            return;
        }
        response.getWriter().write(toDetailJson(product));
    }

    // --- Helpers ---

    private static String trimParam(String s) {
        return s == null ? null : s.trim();
    }

    /**
     * Viết tắt theo tên category để gen SKU / hiển thị: T-Shirt -> TSH, Hoodie -> HD, Quần -> PANTS.
     * Trả về null nếu không khớp mapping.
     */
    private static String derivePrefixFromName(String name) {
        if (name == null || name.isBlank()) return null;
        String n = name.trim().toLowerCase();
        if (n.contains("t-shirt") || n.contains("t shirt") || n.contains("áo thun") || n.contains("thun")) return "TSH";
        if (n.contains("hoodie")) return "HD";
        if (n.contains("quần") || n.contains("pants") || n.contains("pant")) return "PANTS";
        if (n.contains("short")) return "SHT";
        return null;
    }

    /** Prefix cho SKU: ưu tiên viết tắt theo tên (TSH, HD), nếu không có thì dùng code trong DB (nếu khác C1,C2), cuối cùng C + id. */
    private static String getSkuPrefixFromCategory(Category c) {
        if (c == null) return null;
        String fromName = derivePrefixFromName(c.getName());
        if (fromName != null && !fromName.isEmpty()) return fromName;
        String code = c.getCode();
        if (code != null && !code.matches("C\\d+")) return code;
        return "C" + c.getCategoryId();
    }

    /** Code hiển thị bên cạnh tên category: chỉ trả về TSH, HD, PANTS...; trả về "" khi là C1, C2 để không hiện (C1). */
    private static String getDisplayCodeFromCategory(Category c) {
        if (c == null) return "";
        String prefix = getSkuPrefixFromCategory(c);
        if (prefix == null || prefix.matches("C\\d+")) return "";
        return prefix;
    }

    private static Long parseLongOpt(String s) {
        if (s == null || s.isBlank()) return null;
        try {
            return Long.parseLong(s.trim());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private static BigDecimal parseBigDecimal(String s) {
        if (s == null || s.isBlank()) return null;
        try {
            return new BigDecimal(s.trim());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /** 3 ký tự cho variant SKU (VD: Red -> RED). */
    private static String toColorCode(String colorName) {
        String code = colorName.length() >= 3
                ? colorName.substring(0, 3).toUpperCase().replaceAll("[^A-Z0-9]", "")
                : colorName.toUpperCase().replaceAll("[^A-Z0-9]", "X");
        return code.isEmpty() ? "CLR" : code;
    }

    private static String escapeJson(String str) {
        if (str == null) return "";
        return str.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    private static String toDetailJson(ProductDetailDTO product) {
        StringBuilder json = new StringBuilder();
        json.append("{\"productId\":").append(product.getProductId()).append(",");
        json.append("\"sku\":\"").append(escapeJson(product.getSku())).append("\",");
        json.append("\"name\":\"").append(escapeJson(product.getName())).append("\",");
        json.append("\"categoryId\":").append(product.getCategoryId() != null ? product.getCategoryId() : "null").append(",");
        json.append("\"categoryName\":\"").append(escapeJson(product.getCategoryName())).append("\",");
        json.append("\"baseUomId\":").append(product.getBaseUomId() != null ? product.getBaseUomId() : "null").append(",");
        json.append("\"uomName\":\"").append(escapeJson(product.getUomName())).append("\",");
        json.append("\"weight\":").append(product.getWeight() != null ? product.getWeight().toString() : "null").append(",");
        json.append("\"length\":").append(product.getLength() != null ? product.getLength().toString() : "null").append(",");
        json.append("\"width\":").append(product.getWidth() != null ? product.getWidth().toString() : "null").append(",");
        json.append("\"height\":").append(product.getHeight() != null ? product.getHeight().toString() : "null").append(",");
        json.append("\"createdAt\":\"").append(product.getCreatedAt() != null ? product.getCreatedAt().toString() : "").append("\",");
        json.append("\"variants\":[");
        List<dto.ProductVariantDetailDTO> variants = product.getVariants();
        if (variants != null) {
            for (int i = 0; i < variants.size(); i++) {
                dto.ProductVariantDetailDTO v = variants.get(i);
                if (v == null) continue;
                if (i > 0) json.append(",");
                json.append("{\"variantId\":").append(v.getVariantId()).append(",");
                json.append("\"variantSku\":\"").append(escapeJson(v.getVariantSku())).append("\",");
                json.append("\"color\":\"").append(escapeJson(v.getColor())).append("\",");
                json.append("\"colorHex\":\"").append(escapeJson(v.getColorHex())).append("\",");
                json.append("\"size\":\"").append(escapeJson(v.getSize())).append("\",");
                json.append("\"status\":\"").append(escapeJson(v.getStatus())).append("\",");
                json.append("\"totalQtyOnHand\":").append(v.getTotalQtyOnHand() != null ? v.getTotalQtyOnHand().toString() : "0").append(",");
                json.append("\"totalQtyAvailable\":").append(v.getTotalQtyAvailable() != null ? v.getTotalQtyAvailable().toString() : "0").append("}");
            }
        }
        json.append("]}");
        return json.toString();
    }

    @Override
    public String getServletInfo() {
        return "Product management (list, create, edit, variant matrix)";
    }
}
